### ISSUE TITLE
Save audio to file

### ISSUE THREAD

**Issue by DashNY** [KristofferStrube/Blazor.MediaCaptureStreams#4]
Once `MediaStream` is constructed, how do I take the audio and save it to a file on the server? Thanks.

**Comment by KristofferStrube** [comment]
You would have to use the [MediaStream Recording API](https://www.w3.org/TR/mediastream-recording/). I currently don't know of any wrapper for that API for Blazor, but I plan to make one eventually after I'm done wrapping the Web Audio API (which is my current big project). So, for now, you will have to make some JSInterop that calls the relevant methods from the recording API.
