### ISSUE TITLE
Bug: JSException: Could not find 'getReference'

### ISSUE THREAD

**Issue by ham5alpollo** [KristofferStrube/Blazor.MediaCaptureStreams#5]
I keep getting following error in my own application: 
JSException: Could not find 'getReference' ('getReference' was undefined). Error: Could not find 'getReference' ('getReference' was undefined).

**Comment by KristofferStrube** [comment]
Hey @ham5alpollo,

My sample projects use this JS helper function to get `IJSObjectReference`s from `ElementReference`s. You should include it in your project if you want to replicate my samples 1-to-1 like [I have done here](https://github.com/KristofferStrube/Blazor.MediaCaptureStreams/blob/main/samples/KristofferStrube.Blazor.MediaCaptureStreams.WasmExample/wwwroot/index.html#L44):
```js
function getReference(element) { return element; }
```
